---

- name: download rancher cli archive
  get_url:
    dest: "{{ rancher_rke_install_dir }}/rke"
    url: "{{ rancher_rke_download_url }}"
    # checksum: "{{ rancher_cli_checksum }}"

- name: rancher cli is executable
  file:
    path: "{{ rancher_rke_install_dir }}/rke"
    mode: a+x

